# Generated by Django 3.0.8 on 2020-07-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200728_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='passwoed',
            new_name='password',
        ),
    ]
