# Generated by Django 3.0.8 on 2020-07-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='tag',
            new_name='tags',
        ),
    ]
